
--**********************************************************
-- INICIO
--**********************************************************


  
--**********************************************************
-- CREAR HERENCIA


-- HERARQUIA SUPERVISION
GRANT RU_EMPLEADO TO RU_SUPERVISOR;
GRANT RU_CLIENTE TO RU_SUPERVISOR;


-- HERARQUIA GERENCIA
GRANT RU_SUPERVISOR TO RU_GERENTE;


-- HERARQUIA GERENCIA GENERAL
GRANT RU_GERENTE TO RU_GERENTE_GENERAL;
GRANT RU_ADMINISTRADOR_TABLAS TO RU_GERENTE_GENERAL;




--**********************************************************
-- ASIGNACION DE ROLES A LOS USUARIOS


-- ADMINISTRACION DE TABLA

GRANT RU_ADMINISTRADOR_TABLAS TO US_ADMIN_FACTURA;
GRANT RU_ADMINISTRADOR_TABLAS TO US_ADMIN_ENVIO;
GRANT RU_ADMINISTRADOR_TABLAS TO US_ADMIN_CARRITO;
GRANT RU_ADMINISTRADOR_TABLAS TO US_ADMIN_CARRITOPRODUCTO;
GRANT RU_ADMINISTRADOR_TABLAS TO US_ADMIN_DETALLEVENTAS;
GRANT RU_ADMINISTRADOR_TABLAS TO US_ADMIN_FORMAPAGO;

-- USUARIOS DE SISTEMA

GRANT RU_CLIENTE TO US_GENERICO;
GRANT RU_CLIENTE TO US_CLIENTE;
GRANT RU_EMPLEADO TO US_EMPLEADO;
GRANT RU_SUPERVISOR TO US_SUPERVISOR;
GRANT RU_GERENTE TO US_GERENTE;
GRANT RU_GERENTE_GENERAL TO US_GERENTE_GENERAL;

--**********************************************************
-- ASIGNACION DE PERFILES


-- ADMINISTRADORES DE TABLA
ALTER USER US_ADMIN_FACTURA PROFILE PU_ADMINISTRADOR_TABLAS;
ALTER USER US_ADMIN_ENVIO PROFILE PU_ADMINISTRADOR_TABLAS;
ALTER USER US_ADMIN_CARRITO PROFILE PU_ADMINISTRADOR_TABLAS;
ALTER USER US_ADMIN_CARRITOPRODUCTO PROFILE PU_ADMINISTRADOR_TABLAS;
ALTER USER US_ADMIN_DETALLEVENTAS PROFILE PU_ADMINISTRADOR_TABLAS;
ALTER USER US_ADMIN_FORMAPAGO PROFILE PU_ADMINISTRADOR_TABLAS;


-- USUARIOS DE SISTEMA


ALTER USER US_GENERICO profile PU_CLIENTE_GENERICO;
ALTER USER US_CLIENTE profile PU_CLIENTE;
ALTER USER US_EMPLEADO profile PU_EMPLEADO;
ALTER USER US_SUPERVISOR profile PU_SUPERVISOR;
ALTER USER US_GERENTE profile PU_GERENTE;
ALTER USER US_GERENTE_GENERAL profile PU_GERENTE_GENERAL;


--**********************************************************
-- FIN
--**********************************************************

