alter session set "_ORACLE_SCRIPT" = TRUE;
      
CREATE TABLESPACE TBS_FACTURACION
    DATAFILE 'C:\OracleDataBase\Databases\RESTEXP\restexpdata\DF_DATA_FACTURACION01.DBF' SIZE 20M AUTOEXTEND ON,
DEFAULT
    STORAGE ( INITIAL 6M NEXT 4M PCTINCREASE 0 );
      
