alter session set "_ORACLE_SCRIPT" = TRUE;
 
 
--**********************************************************
-- INICIO
--**********************************************************


--**********************************************************
-- CREACION DE TABLA 

-- SELECT TO_DATE(current_date,'yyyy/mm/dd') from dual;


--CREACION DE TABLA ENVIO

CREATE TABLE TB_ENVIO (
    IDENVIO INTEGER NOT NULL ENABLE, 
    IDDETALLEVENTA INTEGER NOT NULL ENABLE, 	
    IDCLIENTE INTEGER NOT NULL ENABLE, 
    ESTADOENVIO VARCHAR2(20 BYTE) NOT NULL ENABLE,
    FECHA         DATE NOT NULL
    )TABLESPACE TBS_FACTURACION_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0)
   PARTITION BY RANGE (FECHA) (
     PARTITION MVM_BEFORE_202201 VALUES LESS THAN (TO_DATE('2022/01/01','yyyy/mm/dd')),
     PARTITION MVM_202201_202202 VALUES LESS THAN (TO_DATE('2022/03/01','yyyy/mm/dd')),
     PARTITION MVM_202203_202204 VALUES LESS THAN (TO_DATE('2022/05/01','yyyy/mm/dd')),
     PARTITION MVM_202205_202206 VALUES LESS THAN (TO_DATE('2022/07/01','yyyy/mm/dd')),
     PARTITION MVM_202207_202208 VALUES LESS THAN (TO_DATE('2022/09/01','yyyy/mm/dd')),
     PARTITION MVM_202209_202210 VALUES LESS THAN (TO_DATE('2022/11/01','yyyy/mm/dd')),
     PARTITION MVM_202211_202212 VALUES LESS THAN (TO_DATE('20213/01/01','yyyy/mm/dd')),
     PARTITION MVM_202301_202302 VALUES LESS THAN (TO_DATE('2023/03/01','yyyy/mm/dd')),
     PARTITION MVM_202303_202304 VALUES LESS THAN (TO_DATE('2023/05/01','yyyy/mm/dd')),
     PARTITION MVM_202305_202306 VALUES LESS THAN (TO_DATE('2023/07/01','yyyy/mm/dd')),
     PARTITION MVM_202307_202308 VALUES LESS THAN (TO_DATE('2023/09/01','yyyy/mm/dd')),
     PARTITION MVM_202309_202310 VALUES LESS THAN (TO_DATE('2023/11/01','yyyy/mm/dd')),
     PARTITION MVM_202311_202312 VALUES LESS THAN (MAXVALUE)
   );

CREATE INDEX IDX_FECHA
          ON MOVIMIENTOS(FECHA)
     STORAGE (INITIAL 5M NEXT 1M PCTINCREASE 0)
  TABLESPACE TBS_INDICES_MOVIMIENTOS;


--**********************************************************
-- CREACION DE INDICE


--CREACION INDICE TABLA ENVIO

CREATE INDEX PK_IDENVIO
    ON TB_ENVIO(IDENVIO)
    STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0)
    TABLESPACE TBS_FACTURACION_IDX;



--**********************************************************
-- CREACION VISTA MATERIALIZADA


-- drop MATERIALIZED VIEW financiamiento_VWM01  


CREATE MATERIALIZED VIEW LOG ON TB_ENVIO
  WITH PRIMARY KEY INCLUDING NEW VALUES;
  
  
CREATE MATERIALIZED VIEW TB_ENVIO_VWM01
       TABLESPACE TBS_FACTURACION_DATA
       BUILD IMMEDIATE
       REFRESH START WITH TO_CHAR(to_date('10-DEC-2022 3:00 AM','DD-MON-YYYY HH:MI AM'),'DD-MON-YYYY HH:MI AM') NEXT TO_CHAR(to_date ('10-DEC-2022 3:00 AM','DD-MON-YYYY HH:MI AM'),'DD-MON-YYYY HH:MI AM') + 1 AS
          select IDENVIO,
                 IDDETALLEVENTA,
                 IDCLIENTE,
                 ESTADOENVIO,
                 FECHA
            from TB_ENVIO;



--**********************************************************
-- ELIMINACION DE TABLE


/*DDROP TABLE TB_ENVIO;/*
/*DROP INDEX PK_IDENVIO;*/


--**********************************************************
-- FIN
--**********************************************************

