alter session set "_ORACLE_SCRIPT" = TRUE;
      
CREATE TABLESPACE TBS_FACTURACION_DATA
    DATAFILE 
    'C:\OracleDataBase\Databases\Oracle19c\oradata\RESTEXP\DATAFILES\FACTURACION\DF_DATA_FACTURACION_01.DBF' SIZE 20M AUTOEXTEND ON
    DEFAULT STORAGE ( INITIAL 6M NEXT 4M PCTINCREASE 0 );
      

CREATE TABLESPACE TBS_FACTURACION_IDX
    DATAFILE 
    'C:\OracleDataBase\Databases\Oracle19c\oradata\RESTEXP\DATAFILES\FACTURACION\DF_FACTURACION_IDX_01.DBF' SIZE 20M AUTOEXTEND ON
    DEFAULT STORAGE ( INITIAL 6M NEXT 4M PCTINCREASE 0 );


/*DROP TABLESPACE TBS_FACTURACION_DATA INCLUDING CONTENTS CASCADE CONSTRAINTS;*/
/*DROP TABLESPACE TBS_FACTURACION_IDX INCLUDING CONTENTS CASCADE CONSTRAINTS;*/