
--**********************************************************
-- INICIO
--**********************************************************


--**********************************************************
-- CREACION DE ROLES

-- ADMINISTRACION DE TABLAS

CREATE ROLE RU_ADMINISTRADOR_TABLAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON FACTURA TO RU_ADMINISTRADOR_TABLAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ENVIO TO RU_ADMINISTRADOR_TABLAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON CARRITO TO RU_ADMINISTRADOR_TABLAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON CARRITOPRODUCTO TO RU_ADMINISTRADOR_TABLAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON DETALLEVENTA TO RU_ADMINISTRADOR_TABLAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON FORMAPAGO TO RU_ADMINISTRADOR_TABLAS;

-- USUARIOS DE SISTEMA

CREATE ROLE RU_EMPLEADO;
GRANT SELECT, INSERT, UPDATE ON FACTURA TO RU_EMPLEADO;
GRANT SELECT, INSERT, UPDATE ON ENVIO TO RU_EMPLEADO;
GRANT SELECT, INSERT, UPDATE ON CARRITO TO RU_EMPLEADO;
GRANT SELECT, INSERT, UPDATE ON CARRITOPRODUCTO TO RU_EMPLEADO;
GRANT SELECT, INSERT, UPDATE ON DETALLEVENTA TO RU_EMPLEADO;
GRANT SELECT, INSERT, UPDATE ON FORMAPAGO TO RU_EMPLEADO;

CREATE ROLE RU_CLIENTE;
GRANT SELECT, INSERT, UPDATE ON FACTURA TO RU_CLIENTE;
GRANT SELECT, INSERT, UPDATE ON ENVIO TO RU_CLIENTE;
GRANT SELECT, INSERT, UPDATE ON CARRITO TO RU_CLIENTE;
GRANT SELECT, INSERT, UPDATE ON CARRITOPRODUCTO TO RU_CLIENTE;
GRANT SELECT, INSERT, UPDATE ON DETALLEVENTA TO RU_CLIENTE;
GRANT SELECT, INSERT, UPDATE ON FORMAPAGO TO RU_CLIENTE;

CREATE ROLE RU_SUPERVISOR;
GRANT SELECT, INSERT, UPDATE ON FACTURA TO RU_SUPERVISOR;
GRANT SELECT, INSERT, UPDATE ON ENVIO TO RU_SUPERVISOR;
GRANT SELECT, INSERT, UPDATE ON CARRITO TO RU_SUPERVISOR;
GRANT SELECT, INSERT, UPDATE ON CARRITOPRODUCTO TO RU_SUPERVISOR;
GRANT SELECT, INSERT, UPDATE ON DETALLEVENTA TO RU_SUPERVISOR;
GRANT SELECT, INSERT, UPDATE ON FORMAPAGO TO RU_SUPERVISOR;

CREATE ROLE RU_GERENTE;
GRANT SELECT, INSERT, UPDATE ON FACTURA TO RU_GERENTE;
GRANT SELECT, INSERT, UPDATE ON ENVIO TO RU_GERENTE;
GRANT SELECT, INSERT, UPDATE ON CARRITO TO RU_GERENTE;
GRANT SELECT, INSERT, UPDATE ON CARRITOPRODUCTO TO RU_GERENTE;
GRANT SELECT, INSERT, UPDATE ON DETALLEVENTA TO RU_GERENTE;
GRANT SELECT, INSERT, UPDATE ON FORMAPAGO TO RU_GERENTE;

CREATE ROLE RU_GERENTE_GENERAL;
GRANT SELECT, INSERT, UPDATE ON FACTURA TO RU_GERENTE_GENERAL;
GRANT SELECT, INSERT, UPDATE ON ENVIO TO RU_GERENTE_GENERAL;
GRANT SELECT, INSERT, UPDATE ON CARRITO TO RU_GERENTE_GENERAL;
GRANT SELECT, INSERT, UPDATE ON CARRITOPRODUCTO TO RU_GERENTE_GENERAL;
GRANT SELECT, INSERT, UPDATE ON DETALLEVENTA TO RU_GERENTE_GENERAL;
GRANT SELECT, INSERT, UPDATE ON FORMAPAGO TO RU_GERENTE_GENERAL;



--**********************************************************
-- FIN
--**********************************************************